### ISSUE TITLE
hidden-by-tab class sync error

### ISSUE THREAD

**Issue by signo** [tmconnect/ACF-Column-Field#1]
I have he following definitions in ACF 5.08 for a custom post type:
field  1 - tab 1
field  2 - col 1/2
field  3 - select
field  4 - select
field  5 - checkboxes
field  6 - col 1/2
field  7 - number
field  8 - select - taxonomy
field  9 - text
field 10 - text
field 11 - tab 2 
field 12 - message
field 13 - col 1/3
field 14 - text
field 15 - col 1/3
field 16 - select
field 17 - col 1/3
field 18 - taxonomy

Here is the problem, the first time i load the page when inserting a new item tab 1 fields are showing and tab 2 fields have the hidden-by-tab class, when i switch to the second tab all fields have the hidden-by-tab class, when i switch back to tab 1 none of the fields show the hidden-by-tab class.
I tried inserting a reset column field before the tab 2, but the reset makes a mess of the last three fields, still showing them in the tab 1.

If you need more info on my part to fix this bug i am available for further testing.

**Comment by signo** [comment]
Tested with acf 5.1.5 and the problem persists.

**Comment by tmconnect** [comment]
I updated the plugin to V 1.0.4 which should solve this bug. Please notice that you have to reset every column group in your field group

ield 1 - tab 1
field 2 - col 1/2
field 3 - select
field 4 - select
field 5 - checkboxes
field 6 - col 1/2
field 7 - number
field 8 - select - taxonomy
field 9 - text
field 10 - text
**new field - col reset**
field 11 - tab 2 
field 12 - message
field 13 - col 1/3
field 14 - text
field 15 - col 1/3
field 16 - select
field 17 - col 1/3
field 18 - taxonomy
**new field - col reset**

Please try the new version and I hope this will work for you.

Thomas

**Comment by signo** [comment]
Hi Thomas, sorry i forgot to update this, i fixed the problem back then adding ',.field_type-tab' to the nextUntil, 

$(root)	.nextUntil('.field_type-column,.field_type-tab')

the problem was that when it reached a tab field it didn't close the column def, i will add the 'reset' column code and test tomorrow.

Cheers
