### ISSUE TITLE
Columns not working on latest ACF

### ISSUE THREAD

**Issue by robhuska** [tmconnect/ACF-Column-Field#3]
I started up a new site with the latest ACF Pro, and the columns are not working. I can see the markup flash when I load the page, but after the js fully loads it is gone and the fields are not placed into columns.

**Comment by robhuska** [comment]
Never mind, I was apparently using the 5.2.6 and older version. Sorry!

**Comment by tmconnect** [comment]
Yes, that's my first thought. Because I already tested the newest version with ACF 5.3.

Your welcome

**Comment by robhuska** [comment]
Great extension btw! It really helps clean up the admin areas. It has been a must use for me for my last 4 sites.

**Comment by robhuska** [comment]
I know I said this before, but now it is for real. Latest update at least (5.3.2.1) breaks the column field. And yes this time I am using the correct version of the extension. It looks like the ACF team did a good bit with restructuring the css. On line 76 of acf-input.css, .acf-fields > .acf-field has a clear: left added to it. And this breaks it.

To fix for now, I added this to a css file that I include in my admin area:

.acf-fields .acf-field.acf-field-columngroup {
	clear: none;
}

Let me know if you have a better way to fix moving forward.

**Comment by tmconnect** [comment]
Fixed this with version 1.1.1 with a slightly different approach, so not all column-groups are affected (especially the clearing column-group)

Thanks for your suggestion!

**Comment by robhuska** [comment]
Thanks for the fast update! I figured you would have a better way to do this, that css was just my hotfix until you had a chance to fix it the right way.
