### ISSUE TITLE
WYSIWYG not working with Flexible Content

### ISSUE THREAD

**Issue by dsamson** [tmconnect/ACF-Column-Field#5]
WYSIWYG is not working when adding new flexible content that contains a WYSIWYG Editor and a Column field.

Example:
Flexible Content
- WYSIWYG 2 columns
--Column 1 (1/2)
--WYSIWYG
--Column 2 (1/2)
--WYSIWYG
--Column Reset (Reset)

If you try to add the above "WYSIWYG 2 column" layout to a page via Flexible content:
Both WYSIWYG editors will be visible but you cannot click or write anything inside the visual tab.

Once you save the page then both WYSIWYG's will work as they should, but is not best practice for client to have to do this step each time to add content.

Is there a way to get the WYSIWYG to fire dynamically each time new flexible content is added to the page using the column fields?

**Comment by tmconnect** [comment]
Yes, I know about this behavior - but I didn't find any solution for that.

It's a problem of tinyMCE editor, which doesn't like to be moved within the DOM.

Maybe there's someone outside who knows how to solve this.

**Comment by dsamson** [comment]
Just added a pull request for this issue. Let me know your thoughts.

**Comment by tmconnect** [comment]
Thanks for your input I found in your forked version. It's more efficient to include your request here in the original.

I included your idea into the new version.
